### ISSUE TITLE
单个服务无法调用多重参数

### ISSUE THREAD

**Issue by badafans** [HyNetwork/hysteria#129] opened 2021-09-12 13:09 UTC
{
	"server": "serverip:443",
	"obfs": "your password",
	"up_mbps": 30,
	"down_mbps": 120,
	"insecure": true,
	"relay_tcp": [
		{
			"listen": "0.0.0.0:443",
			"remote": "127.0.0.1:443",
			"timeout": 300
		},
		{
			"listen": "0.0.0.0:1080",
			"remote": "127.0.0.1:1080",
			"timeout": 300
		}
	]
}

同一种方法，无法配置多个服务。希望增加对同一种方法的多个参数的重复支持

**Comment by tobyxdd** [comment] 2021-09-14 06:26
Actually this is a duplicate of #108 so I'm gonna close it here

**Closed by tobyxdd** 2021-09-14 06:26 UTC
Labels: enhancement
